import {Teeup} from './teeup'

export var TEEUPS: Teeup[] = [
    {
        id: 0,
        name: "Brainstorming Session",
        decision: 2,
        going: 3,
        msgCount: 5,
        msgLikeNumber: 2,
        wtfIsThis: 2,
        date: "Mon Feb 25, 3:00PM",
        location: "Student Center 2F",
        time: '5m',
    },
    {
        id: 1,
        name: "Movie Night Out",
        decision: 2,
        going: 4,
        msgCount: 5,
        msgLikeNumber: 8,
        wtfIsThis: 1,
        date: "Sun Feb 7, 7:00PM",
        location: "AMC Time Square",
        time: '3m',
    },
    {
        id: 2,
        name: "Indoor Volleyball",
        decision: 2,
        going: 11,
        msgCount: 15,
        msgLikeNumber: 0,
        wtfIsThis: 0,
        date: "Sunday Feb 7, 7:00PM",
        location: "AMC Time Square",
        time: '2h',
    },
    {
        id: 3,
        name: "Ultimate Bowl-Down",
        decision: 2,
        going: 3,
        msgCount: 5,
        msgLikeNumber: 8,
        wtfIsThis: 0,
        date: "Sunday Feb 7, 7:00PM",
        location: "AMC Time Square",
        time: '2h',
    },
    {
        id: 4,
        name: "Gojira Maraton!",
        decision: 2,
        going: 3,
        msgCount: 5,
        msgLikeNumber: 8,
        wtfIsThis: 1,
        date: "Sat Feb 18, 11:00AM",
        location: "Gretchen's Place",
        time: '2h',
    }
];
